# Promtail config
server:
  disable: true

positions:
  filename: /tmp/promtail-positions.yaml

clients:
  - url: http://192.168.1.16:3100/loki/api/v1/push

scrape_configs:
- job_name: authlog
  static_configs:
  - targets:
      - localhost
    labels:
      job: authlog
      shipper: promtail
      __path__: /var/log/auth.log

- job_name: daemonlog
  static_configs:
  - targets:
      - localhost
    labels:
      job: syslog
      shipper: promtail
      __path__: /var/log/daemon.log
