
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.26.0.3      # Add the IP address of the proxy server
    - 172.30.33.0/24  # You may also provide the subnet mask
    - 172.26.0.0/24

camera: !include cameras.yml

influxdb:
  host: "192.168.1.16"
  port: 8088
  database: GarminStats
  username: friday
  password: eQQenqw6JDcYiEr4sLT3WYtvLCs
  ssl: false
  verify_ssl: false
  max_retries: 3
  include:
    entities:
       - sensor.garmin_device_battery_level
  tags:
    source: hass
